src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContactRepository::class)]
class Contact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $Nom = null;

    #[ORM\Column(length: 100)]
    private ?string $email = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $message = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }
}

src/Controller/NosPartenairesController.php
<?php

namespace App\Controller;

use App\Entity\Partenaire;
use App\Form\PartenairesFormType;
use App\Repository\PartenaireRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class NosPartenairesController extends AbstractController
{
    #[Route('/nospartenaires', name: 'app_nos_partenaires')]
    public function index(Request $request, EntityManagerInterface $entityManager, PartenaireRepository $partenaireRepo ): Response
    {
        $partenaire = new Partenaire();
        $form = $this->createForm(PartenairesFormType::class, $partenaire);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $entityManager->persist($partenaire);
            $entityManager->flush();
        }

        //on appel la liste de tous les partenaires
        $partenaires = $partenaireRepo->findAll();

        return $this->render('nos_partenaires/index.html.twig', [
            'partenaires' => $partenaires,
            'partenaireForm' => $form->createView()
        ]);

    }
}

templates/nos_partenaires/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos Partenaires{% endblock %}

{% block body %}

    <h2 class="titre">Nos Partenaires</h2>
    <div class="container">
        {% for partenaire in partenaires %}
            <a href="{{ partenaire.siteweb }}"> <img src="{{ partenaire.logo() }}" alt="{{ partenaire.nom }}"/></a>
        {% endfor %}
    </div>

    <div class="formulaire">
    <div class="inscription">
        <h2>Devenez partenaire</h2>
        <h3>    </h3>
        <div class="form">
            {{ form_start(partenaireForm) }}
            <div class="nom">
                {{ form_widget(partenaireForm.nom, {'attr': {'placeholder': 'Nom'}}) }}
                <span class="material-symbols-outlined"> groups </span>
            </div>
            <div class="adresse">
                {{ form_widget(partenaireForm.adresse, {'attr': {'placeholder': 'Adresse'}}) }}
                <span class="material-symbols-outlined"> location_on </span>
            </div>
            <div class="contact">
                {{ form_widget(partenaireForm.contact, {'attr': {'placeholder': 'Contact'}}) }}
                <span class="material-symbols-outlined"> mail </span>
            </div>
            <div class="dons">
                {{ form_widget(partenaireForm.dons, {'attr': {'placeholder': 'Dons'}}) }}
                <span class="material-symbols-outlined"> redeem </span>
            </div>
            <div class="dons">
                {{ form_widget(partenaireForm.logo, {'attr': {'placeholder': 'Logo'}}) }}
                <span class="material-symbols-outlined"> image </span>
            </div>
            <div class="dons">
                {{ form_widget(partenaireForm.siteweb, {'attr': {'placeholder': 'Site Web'}}) }}
                <span class="material-symbols-outlined"> link </span>
            </div>
                <button type="submit" class="btn">Envoyer</button>
        </div>
    </div>

    {{ form_end(partenaireForm) }}
    </div>

    <style>
        body{
            background: #191919;
        }
        .titre{
            color: rgba(255, 255, 255, 0.38);
            font-size: 36px;
            font-weight: 500;
            margin: auto;
            margin-top: 10%;
        }
        .container{
            margin : auto;
            margin-top:2%;

            display: grid;
            grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
            gap: 5px 2em;    align-items: center;

        }
        .container:first-child {
            align-self: center;
        }
        img{
            width: 200px;
        }
        @keyframes rotate {
            100% {
                background-position: 15% 50%;
            }
        }

        .formulaire{
            background-image: url({{ asset('images/waves.svg')}});
            background-size: 130rem;
            background-repeat: no-repeat;
            animation: rotate 6s infinite alternate linear;
        }
        .inscription {
            position: relative;
            margin : auto;
            margin-top: 5%;
            margin-bottom: 2%;
            z-index: 3;
            padding: 38px 30px 44px;
            border-radius: 22px;
            background: #161616;
            text-align: center;
            width: 380px;
        }

        .inscription > h2 {
            color: rgba(255, 255, 255, 0.38);
            font-size: 36px;
            font-weight: 500;
            margin: 0 0 4px;
        }

        .inscription > h3 {
            color: rgba(255, 255, 255, 0.38);
            margin: 0 0 30px;
            font-weight: 500;
            font-size: 16px;
        }

        form {
            display: grid;
            gap: 16px;
            place-items: center;
            width: 100%;
            margin: 0;
        }

        .nom, .adresse, .contact, .dons {
            color: rgba(255, 255, 255, 0.38);
            width: 100%;
            position: relative;
        }

        span {
            position: absolute;
            top: 50%;
            left: 16px;
            translate: 0 -50%;
            color: rgba(255, 255, 255, 0.38);
        }

        form input,
        form button {
            width: 100%;
            height: 60px;
            outline: none;
            padding: 0;
            font-family: inherit;
            font-size: 16px;
            border-radius: 8px;
        }

        form input {
            background: transparent;
            border: 2px solid rgba(255, 255, 255, 0.1);
            font-size: 18px;
            padding: 0 20px 0 50px;
            color: inherit;
        }

        form input:focus {
            border-color: #4b4c4d;
        }

        form input:focus ~ span {
            color: #8e44ad;
        }

        form textarea {
            background: transparent;
            border: 2px solid rgba(259, 255, 255, 0.1);
            font-size: 18px;
            padding: 18px 20px 0 50px;
            color: inherit;
            height: 60px;
            width: 319px;
            resize : none;
            border-radius : 8px
        }



        form textarea:focus {
            outline: none;
            border-color:#4b4c4d;
        }

        form textarea:focus ~ span {
            color: #8e44ad;
        }


        form button {
            cursor: pointer;
            background: rgba(255, 255, 255, 0.38);
            color: #f9f9f9;
            border: 0;
            font-weight: 600;
            letter-spacing: 2px;
        }

    </style>
{% endblock %}